apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: todoapp-app:latest # Make sure this image is available to your cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-storage
              mountPath: /var/www
      volumes:
        - name: app-storage
          hostPath:
            path: /run/desktop/mnt/host/d/xampp/htdocs/todoapp
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
